server:
  port: 8090
  servlet:
    contextPath: /

mysql:
  service:
    host:     ibproducto-db-server
    port:     3306
    database: ibproducto_reports

spring:
  jersey:
    application_path: /api  
  datasource:
    url:      jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${mysql.service.database}?autoReconnect=true&useSSL=false
    jdbcUrl:      jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${mysql.service.database}?autoReconnect=true&useSSL=false
    username: ibproducto
    password: ibproducto123
    maxActive: 50
    maxIdle: 5
    maxWait: 1000
    validationQuery: "select 1"
    testOnBorrow: true
    testOnConnect: true
    testWhileIdle: true
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
      time-between-eviction-runs-millis: 36000
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate.show_sql: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    
websked:
  config:
    token:  MQ497B6G1G5RAHG0NCR5063G5OIBPR553RCZIrF7JXY0OLUzn1YzhYilS+dGaHIoMyPLKfKv
    url:    https://api.infobae.arcPublishing.com/websked